# Originally based on this recipe:
#  https://anaconda.org/HCC/midnight-commander/files

{% set name = "midnight-commander" %}
{% set version = "4.8.25" %}
{% set sha256 = "407dc20f70082f26c7f5716406cb755cbb6cba3f2f13b841b79a991282d310c2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.midnight-commander.org/mc-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx or win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - perl
    - python
  host:
    - slang
    - gettext
    - glib
    - libssh2
    - zip
    - unzip
    - gpm
    - zlib
    - libiconv
  run:
    - slang
    - gettext
    - glib
    - libssh2
    - zip
    - unzip
    - zlib
    - libiconv

test:
  commands:
    - mc --version

about:
  home: https://midnight-commander.org
  dev_url: https://github.com/MidnightCommander/mc
  summary: "GNU Midnight Commander is a visual file manager, licensed under GNU General Public License and therefore qualifies as Free Software. It's a feature rich full-screen text mode application that allows you to copy, move and delete files and whole directory trees, search for files and run commands in the subshell. Internal viewer and editor are included."
  license: GPLv3
  license_family: GPL
  license_file: COPYING
